version: '3'
services:
  redis:
    image: redis
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --appendfsync everysec --save 900 1 --save 300 10 --save 60 10000
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  serverless-redis-http:
    ports:
      - 8079:80
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: development
      SRH_CONNECTION_STRING: redis://redis:6379 # Using `redis` hostname since they're in the same Docker network.

volumes:
  redis_data:
    driver: local
