import type { RegionSettings } from "../index.js";

export default {
  // Turkey - Celsius
  "TR-01": { temperature: "c" }, // Adana
  "TR-02": { temperature: "c" }, // Adıyaman
  "TR-03": { temperature: "c" }, // Afyonkarahisar
  "TR-04": { temperature: "c" }, // Ağrı
  "TR-05": { temperature: "c" }, // Amasya
  "TR-06": { temperature: "c" }, // Ankara
  "TR-07": { temperature: "c" }, // Antalya
  "TR-08": { temperature: "c" }, // Artvin
  "TR-09": { temperature: "c" }, // Aydın
  "TR-10": { temperature: "c" }, // Balıkesir
  "TR-11": { temperature: "c" }, // Bilecik
  "TR-12": { temperature: "c" }, // Bingöl
  "TR-13": { temperature: "c" }, // Bitlis
  "TR-14": { temperature: "c" }, // Bolu
  "TR-15": { temperature: "c" }, // Burdur
  "TR-16": { temperature: "c" }, // Bursa
  "TR-17": { temperature: "c" }, // Çanakkale
  "TR-18": { temperature: "c" }, // Çankırı
  "TR-19": { temperature: "c" }, // Çorum
  "TR-20": { temperature: "c" }, // Denizli
  "TR-21": { temperature: "c" }, // Diyarbakır
  "TR-22": { temperature: "c" }, // Edirne
  "TR-23": { temperature: "c" }, // Elazığ
  "TR-24": { temperature: "c" }, // Erzincan
  "TR-25": { temperature: "c" }, // Erzurum
  "TR-26": { temperature: "c" }, // Eskişehir
  "TR-27": { temperature: "c" }, // Gaziantep
  "TR-28": { temperature: "c" }, // Giresun
  "TR-29": { temperature: "c" }, // Gümüşhane
  "TR-30": { temperature: "c" }, // Hakkâri
  "TR-31": { temperature: "c" }, // Hatay
  "TR-32": { temperature: "c" }, // Isparta
  "TR-33": { temperature: "c" }, // Mersin
  "TR-34": { temperature: "c" }, // Istanbul
  "TR-35": { temperature: "c" }, // İzmir
  "TR-36": { temperature: "c" }, // Kars
  "TR-37": { temperature: "c" }, // Kastamonu
  "TR-38": { temperature: "c" }, // Kayseri
  "TR-39": { temperature: "c" }, // Kırklareli
  "TR-40": { temperature: "c" }, // Kırşehir
  "TR-41": { temperature: "c" }, // Kocaeli
  "TR-42": { temperature: "c" }, // Konya
  "TR-43": { temperature: "c" }, // Kütahya
  "TR-44": { temperature: "c" }, // Malatya
  "TR-45": { temperature: "c" }, // Manisa
  "TR-46": { temperature: "c" }, // Kahramanmaraş
  "TR-47": { temperature: "c" }, // Mardin
  "TR-48": { temperature: "c" }, // Muğla
  "TR-49": { temperature: "c" }, // Muş
  "TR-50": { temperature: "c" }, // Nevşehir
  "TR-51": { temperature: "c" }, // Niğde
  "TR-52": { temperature: "c" }, // Ordu
  "TR-53": { temperature: "c" }, // Rize
  "TR-54": { temperature: "c" }, // Sakarya
  "TR-55": { temperature: "c" }, // Samsun
  "TR-56": { temperature: "c" }, // Siirt
  "TR-57": { temperature: "c" }, // Sinop
  "TR-58": { temperature: "c" }, // Sivas
  "TR-59": { temperature: "c" }, // Tekirdağ
  "TR-60": { temperature: "c" }, // Tokat
  "TR-61": { temperature: "c" }, // Trabzon
  "TR-62": { temperature: "c" }, // Tunceli
  "TR-63": { temperature: "c" }, // Şanlıurfa
  "TR-64": { temperature: "c" }, // Uşak
  "TR-65": { temperature: "c" }, // Van
  "TR-66": { temperature: "c" }, // Yozgat
  "TR-67": { temperature: "c" }, // Zonguldak
  "TR-68": { temperature: "c" }, // Aksaray
  "TR-69": { temperature: "c" }, // Bayburt
  "TR-70": { temperature: "c" }, // Karaman
  "TR-71": { temperature: "c" }, // Kırıkkale
  "TR-72": { temperature: "c" }, // Batman
  "TR-73": { temperature: "c" }, // Şırnak
  "TR-74": { temperature: "c" }, // Bartın
  "TR-75": { temperature: "c" }, // Ardahan
  "TR-76": { temperature: "c" }, // Iğdır
  "TR-77": { temperature: "c" }, // Yalova
  "TR-78": { temperature: "c" }, // Karabük
  "TR-79": { temperature: "c" }, // Kilis
  "TR-80": { temperature: "c" }, // Osmaniye
  "TR-81": { temperature: "c" }, // Düzce
} satisfies Record<string, RegionSettings>;
